name: Test_and_build
on: [push]

permissions:
  checks: write
  contents: write

jobs:
  Test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: pip install black flake8 dnspython

      - name: Python Linters
        uses: wearerequired/lint-action@v1
        with:
          black: true
          flake8: true

      - name: List files
        run: mkdir _data; ls -lha *
      - name: Build
        run: python generator/generate.py
      - name: List files post build
        run: ls -lha *; cat _data/*
